remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
include:
- _posts
- _layouts

title: CS with Mr Teasdale
description: CS, Programming, and CySec stuff for my classes